apiVersion: v1
kind: Secret
metadata:
    name: cluster-user-auth
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:5q2MFVM=,iv:ArP5vc8zwsXJYfXv3r9Xm79gE2jkDhlmTANc3K/G+tM=,tag:f3FoR4VqrzCpCACd8rN9AA==,type:str]
    password: ENC[AES256_GCM,data:9Oh+QIKtkQZDHUSMJmw93xo368amtxGkrlHBsieQm6j9ksM+xFTOMmB2xERcpOewHti9RnVxRcbLPcdn,iv:9Av847HNlERdksE/apyQLClmZr+RfpDLPQKn+6l6PJQ=,tag:+7gF/HXTB1QUnIyzyWu+Nw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1kh9qxg0nplvlncvld27lg3h4f3epdsr32vuxswtxn95fyhj04ufsuq9cl6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKVGduSGF2c0g1RUN3M2tH
            MnlTcytoZzhDU1RrOGE2V2ZDNlVsOUxNZ0c0ClNVbmhvbXNTeVpjVGtKSVAxMGJN
            em1OZWNaVmYvbFEvNmxiUVlzUFN4NkkKLS0tIGRGMEg1SjJXdno3RkQ5bGxQRDg2
            R2t2RVhuOGxjZkJMbGdDN084ZlBHdzgKP3IeRBf9pNWw+/cXyWGJHnzYDC53ZYV7
            d6SQMaHbAJKRRf46lT/sZDI1lOBs+Qc5YY7M2y/IYgMFTEUPFEYfFw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-24T06:46:59Z"
    mac: ENC[AES256_GCM,data:bjjjUt6gU/jlgqk0vFp8eqlF8FYeMuZ4bJ72ZBRagEB5ovRIpOlfeFjTOXvMjv8SZ3EghlqALsDpZOqcMqy4bTiLhL4ZoaN8Ps1CleJb1gyFizNnOOlsGO/rwUcW36d32whUJN8/xUy2Za/2Ojq8nSZDRk4E4hNEo/yOHhOGdus=,iv:dG9rfRGsq91EB5TDUWSBo1pfHnYgWenVkkT3uI9Qvlo=,tag:NH2C8vSGf4DzG6voiRUkyw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
