apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECERT_ARGOCD_ADMIN_PASSWORD: ENC[AES256_GCM,data:WRNUrlbolg7TdrX5F569DE6fiJrvGr5UOJgbcL2ZwjmZAYJcJdqWNLqygCF1+wq+4uQinDhpbmdvsp6p,iv:NGBdhu85JDpr2uxgRtBx7e5iJBW6PX+umGki3apFfJs=,tag:z7LMqglVeiwji9K/suO9oQ==,type:str]
    GITHUB_WEBHOOK_TOKEN: ENC[AES256_GCM,data:OSTciqEMKP3SHp4QD6F4xwykWPw6pt3N6fyMLVBfSfc=,iv:ao3D1fbijOdRomNVKFVazHa5QUUVy0xCZHAU9rwV6Us=,tag:bXFJ8KWxdBa+5wcnx7MDcQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1kh9qxg0nplvlncvld27lg3h4f3epdsr32vuxswtxn95fyhj04ufsuq9cl6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPWVZMdmUwa3hQMXJDdHR3
            VU12UVB5WkxQT3dtTkhjTXNaQStCM05Fc1hnCklDNVI1R1pMYjFJNVVCUHNlYzFQ
            YVYyZ2dreG9ESGtYRkdNUUpUQno3YlUKLS0tIDl1SUFqa0MyY1lreDlIRE53SFFG
            dHhFSDR1TWlsRDB5ZVhnejdDb1VZS00K7StjVCLz9nqttsyoP5QHbjbTy8Scb/jQ
            YRwIPntcbs7r6s7hJ0jowtyFVU5Fh9pkH5bu6g1TzbsVguvHTui4PA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-24T06:33:30Z"
    mac: ENC[AES256_GCM,data:b6h/l6OQCo5OlHKTM+dsXukBXO/FerMEEMjaEEH/eMfYIB61keusskPLtxYNN2wDWCM1WkfiHI8oi9cFOBw0iew0jCGS6IdsgONu1iun0oIU2etmEsQdVW/GG+/C/pzdKVtXLYBXUSCUWqd1wH2K7/8mHKlVwcu0bRYej8FYiPs=,iv:RbiYHCzDLANojx+S50FUnBnePO2owtyDo0X8E5+D1vE=,tag:t1PwyTyCxez5FwPrvuKoOQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
