apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECERT_ARGOCD_ADMIN_PASSWORD: ENC[AES256_GCM,data:WCP3i04RWuPJOd/x6H1OcH0lp9qS/6dlz5WISHiyGWqz4OPBjysBOgJULyT7fE3icYKmfuGzOcNJssNo,iv:phJYIb/n6O0u2qQnc9eCWcFmYfRhEewz5OsLa2bAqwY=,tag:9U8cKIoTkMQsum0/w3OJNg==,type:str]
    GITHUB_WEBHOOK_TOKEN: ENC[AES256_GCM,data:hBwjzb6bAnwushITC1kaCzwAErr5MAhgiOM50EvEroc=,iv:b2fXTiTjvOaLAWV8iaGNE5PsbK9UrUZmu8onsaraTMA=,tag:pztB+ZqyFZvJA0zou8wbYQ==,type:str]
    NFS_SERVER: ENC[AES256_GCM,data:Z8CzHJ9xzc2WPug=,iv:TmMsjcEuEc6ozxhP6vUZmnGpIRSBxS2fff+2UcHBw4Y=,tag:v3J2p0kIqAwmqGIlXm6Rqw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1kh9qxg0nplvlncvld27lg3h4f3epdsr32vuxswtxn95fyhj04ufsuq9cl6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDcS9CeU1zQld1ZlNrc2JN
            VjhMMytBMy9TcklwZG1pRGxvVmdHNWhETjBFCk9GQ3I0ejZFaDV3OWNCM1lRRllB
            ZjhwcXRzVFJhbmhYcXVoV2VqbEV4OU0KLS0tIEJDc1FMdmpsM1JOb2R5aHhOb2Zi
            Umh3SUNSK1k2VXRaVXZ1T29LZWROUWsK2ftcgNqeH9tIA/mb0Ma6QLR9MPtAqzec
            w47Aq+LV5ilWZ/5czK3NgVeteVQUO0Vv4eIxGuMOcUcQoTHTxfPOEQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-25T06:41:08Z"
    mac: ENC[AES256_GCM,data:yMQy2zFjOpick3Ai09YRJUk8jzJInO/5dMPliUwbUGF5CNpy7lOxC84SULl7TSARZsepOs8esPXgGqb0xL1kJV+wrNPG44HMaB4A3D/YuHjrsP0+HBHbyM5CtGIbHkEVX8blhFLwzja/bziUU8tHQUOEbs6ugGF9+uQNim8iIRQ=,iv:ouAnqM2Z9sHrTAO6BmGHeN+Vw3k/dCXAzfi15rLeeFw=,tag:fzJshFZ/mjkmxGCJMD31DA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
